#!/usr/bin/env bash
# Automate fix for server to listen on port 80
rm /etc/nginx/sites-enabled/default
ls -n /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart