#!/usr/bin/env bash
# Configure nginx server redirecting to another page
sudo apt-get -y install nginx
sudo service nginx start
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "53i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart 
sudo service nginx reload
